version: '3.9'

services:
  app:
    build: npm run start:sample
    image: node:20-alpine3.17
    container_name: app
    working_dir: /src
    volumes:
      - .:/src
    command: ["npm", "run", "start:samples"]